---
- hosts: all
  tasks:
  - name: make sure chronyd is installed
    yum:
      name: chrony
      state: latest
      update_cache: yes

  - name: deploy chrony.conf template
    template:
      src: /ansible/files/chrony.conf.orig
      dest: /etc/chrony.conf
      owner: root
      group: root
      mode: 0644
      backup: yes

  - name: Restart chronyd
    service:
      name: chronyd
      state: restarted

  - name: Enable service chronyd
    service:
      name: chronyd.service
      enabled: true
